[book]
authors = ["vxpm"]
language = "en"
multilingual = false
src = "src"
title = "cubenotes"

[preprocessor.alerts]

[preprocessor.pagetoc]

[output.html]
additional-css = ["theme/pagetoc.css", "theme/custom.css"]
additional-js = ["theme/pagetoc.js", "theme/custom.js"]
smart-punctuation = true
git-repository-url = "https://github.com/vxpm/cubenotes"
